### ISSUE TITLE
Recent mu4e commit broke search

### ISSUE THREAD

**Issue by wavexx** [djcb/mu#1140]
Starting with commit 457a0a17a2954959cee87bad285679d1fc85d7b4, it seems that any query in mu4e containing an unquoted space will stop at the first token.

Just to make it obvious:

- test [works]
- more test [will only find "more"]
- "more test" [works]

Only mu4e seems affected, search terms work correctly from the cli.

**Comment by joostkremers** [comment]
I seem to be running into the same problem: if I search in mu4e for `flag:unread AND NOT flag:trashed`, I get trashed messages. From the command line with `mu find`, it works correctly.

**Comment by thierryvolpiatto** [comment]
Joost Kremers <notifications@github.com> writes:

> I seem to be running into the same problem: if I search in mu4e for flag:unread AND NOT flag:trashed, I get trashed messages. From the command line with mu find, it
> works correctly.

Now I could finally build and install I have the same behavior with:

"flag:unread AND NOT flag:trashed AND NOT maildir:/Gmail/[Gmail].Spam AND NOT maildir:/Gmail/[Gmail].All \
AND NOT /Yahoo/Bulk Mail Mail"

All trashed, spam, all and bulk are coming up.

-- 
Thierry

**Comment by djcb** [comment]
Yeah, it's some protocol mismatch between mu4e / mu... I've pushed a work-around fix.

**Comment by joostkremers** [comment]
The query `flag:unread AND NOT flag:trashed` now seems to work, but the following doesn't get me the results I expect:

    maildir:/Fastmail/Inbox OR (maildir:/UniGoe/Inbox OR maildir:/UniWuppertal/Inbox)

The parens are put there by `mu4e-query-fragments`. (Note though, that I get the same result when I enter the query manually.) If I remove the parents, I get different results, but still wrong ones.

On the command line, everything works.

**Comment by djcb** [comment]
Oh, that's silly... I've pushed a fix. Please try again.

**Comment by joostkremers** [comment]
Yeah, that seems to have solved it. Thanks!

**Comment by tuxella** [comment]
I think I ran into a related problem also:

I built the last version of mu and mu4e (commit af4f12c696666628e7f5e656f092928b79b38127) and since then some mu4e queries won't work.

For instance (queries are ran from the shell):

- `mu find "flag:unread"` returns 2 messages 
- `mu find 'date:10h..now'` returns 4 messages (including 2 unread messages that appeared in the previous query)
- `mu find "flag:unread OR date:10h..now"` returns 0 messages


I am running on macOS 10.13 and built mu using g++ version 7.2.0 against Xapian 1.4.5 (built using the same g++)

**Comment by djcb** [comment]
I've bumped the mu version to 1.0-alpha, so mu and mu4e should stay in agreement.

**Comment by djcb** [comment]
Okay, it seems to work now... closing this.
