### ISSUE TITLE
mu cfind produces seemingly incomplete results

### ISSUE THREAD

**Issue by john-at-charpa** [djcb/mu#2201]
I'm using mu cfind from mutt's query command. However, I suspect that somehow the way contacts are stored is producing non-optimal results. When comparing the output from:

mu cfind $query 
to 
mu find from:$query -f f

I can end up with considerably different results. I have read the man page where it says "In case the same e-mail address is used with different names, the most recent non-empty name is used.", but I don't this quite covers the issue.

For example:

$ mu cfind jvdl
jvdl@company.com jvdl@company.com
jvdl@personaladdress.com
Joost van der Lande jvdl@internalhost.company.com

$ mu find -u -q from:jvdl -f f | sort | uniq
Joost van der Lande <jvdl@company.com>
Joost van der Lande <jvdl@internalhost.company.com>
Joost van der Lande <jvdl@peronsaladdress.com>
Joost vanderLande <jvdl@company.com>

I realize I'm kind of cheating by grinding through the from headers, but the purpose is to show that the source data is indeed indexed yet not appearing in the cfind output.

*Environment*
mu: mu v1.6.10
os: macOS Big Sur
mail format: Maildir

**Comment by djcb** [comment]
Hmmm... when you do a re-init of the database (with `mu init`), and re-index, do the missing contacts show up?

**Comment by john-at-charpa** [comment]
Ugh, you are completely correct. I was half way through writing "I've tried that", when I decided to do it again. When I noticed this happen for the first time I simply rm -rf'd everything. Then re-init'd the db and re-indexed. When the results were the same I filed this, but clearly did something incorrectly. Apologies for the wasted time.

**Comment by djcb** [comment]
There may still be a problem (since a re-init shouldn't be necessary)... but I'll close it now. Fee free to re-open if you see it again.

**Comment by john-at-charpa** [comment]
Well, there's good news and bad news. The good news is that it appears I'm not insane. The bad news is that this morning I ran a mu cfind and we're back to the previous state. I suspect that the problem is (maybe) the periodic indexing from cron. My crontab looks like:

*/15 * * * * /opt/local/bin/mu index --lazy-check > /dev/null 2>&1

Unfortunately I've shot myself in the foot redirecting output. I'm going to re-init the DB, re-index, then switch the cron job to run mu -d index and without the redirect. Perhaps it will log something. 

I have looked at  ~/.cache/mu/mu.log and there is nothing reported other than the indexer runs. If there's anything else you'd like me to set I'm happy to give it a go.

**Comment by djcb** [comment]
Periodic indexing like that should work, but are your perhaps killing mu and some cases or does it otherwise shutdown ungracefully? I did some changes that may help for that.

Another thing you could test, if there's a message which you thing has addresses that `mu cfind` does not, please use `mu add path-to-message-file` and then check if mu cfind can find them.

**Comment by john-at-charpa** [comment]
Well, things just got weird. Today things are fixed again - despite no reindexing. I had the -d flag in the wrong location so there are no debug logs yet.  I've reset the db yet again and after verifying that the mu.log had debug information in it created a second cron job to tell me when the previously mentioned email address 'breaks' again.

I messed around with the data to look for some patterns and I can at least tell you that I've noticed the following behavior:

* Running mu init, mu index does not always work. I mentioned that I had done it in the past, but mistakenly thought I hadn't done it correctly. After testing it seems that I get inconsistent results. Sometimes the addresses are correct right after indexing, other times they are missing. I can pave and index again and again and get the same (incorrect) results 3 or 4 times in a row, but then after time it is suddenly OK. Other times it can stay broken for almost an entire day.

* The breakage (missing) seems to be broken in the same way for all addresses that show up that way. Basically when broken it is: 

address@domain.com address@domain.com

but when (randomly) fixed it is:

Display Name address@domain.com

There is a lot of email from cron jobs and internal machines that may only have a header like
To: address@domain.com, so I'm beginning to suspect that if the indexing finds this "no display name" version first, then then queries return that - yet if Display Name address@domain.com is found first, that is the one that ends up as the key/value. Since this is just indexing thousands of flat files (Maildir) I could see where random file uptake order might trigger this. I've not spent enough time reading the source, so this is just (bad?) guess work.

**Comment by john-at-charpa** [comment]
I forgot to mention that attempted a "mu add" on a message that had a correctly formed Display Name address@domain.com, but it had no effect on the output of mu cfind. I suspect this is because the entry isn't missing, just missing a Display Name version.

**Comment by john-at-charpa** [comment]
Sure enough, this morning I checked and it's flipped back to address@domain.com address@domain.com. My cfind check from cron caught it changing at 6:20AM, so it's been fine for nearly? 24 hours. At 6:15 a lazy index ran and it logged two new indexed messages (details slightly obscured):

2022-01-20 06:15:00 ** (mu:4764): DEBUG: 06:15:00.782: created message from /Users/jcw/mail/Mailbox-Name/new/1642626204.4733_1.hostname,U=1499:2, in 1685 ?s
2022-01-20 06:15:00 ** (mu:4764): DEBUG: 06:15:00.788: created message from /Users/jcw/mail/Mailbox-Name/new/1642626785.4755_1.hostname,U=1500:2, in 462 ?s

Sure enough, the To line on the first message above included the undesired address:
<snip>
To: "someone@company.com" <someone@company.com>,
        "jvdl@company.com" <jvdl@company.com>,
<snip>

So that explains the behavior. 

Obviously I have no control over people addressing messages like this (or anything else that breaks RFCs or is just an undesirable practice). I am not sure how this could be worked around - aside from a) storing multiple entries b) some kind of brain twisting logic for the indexer. Rats :(

**Comment by djcb** [comment]
Okay... so I guess there's not much we can do about it automatically;  but note that mu4e has e.g. `mu4e-contact-process-function` which you can use to make the address a bit more palatable in such cases.

**Comment by eslgastal** [comment]
Hello @john-at-charpa and @djcb .

Sorry to comment on an old issue, but I believe the problem still exists and it has been bugging me (at least on 1.10.9 - release/1.10).

One thing that seems to have solved the problem for me was to update the contacts cache only when `contact.type == Contact::Type::From`. That is, we get the contact's name only from messages sent by them. More precisely, I've substituted

```C++
if (contact.message_date > existing.message_date &&
    contact.type == Contact::Type::From) {	// update?
```

for

https://github.com/djcb/mu/blob/fb76210138c87aaf3056899bb78a3f13b7fbe1ef/lib/mu-contacts-cache.cc#L216

Unfortunately this works at the cache level and requires a re-indexing (re-init). Working at the level of the cfind cmd would be better I think.

Best,
Eduardo

**Comment by djcb** [comment]
`mu` gathers the contact-info from the messages in its database, and it prefers the last seen address; so something worth trying as a work-around would be to create a fake message with some future date and with the desired addresses/names in To:/Cc: etc.
