### ISSUE TITLE
[mu4e bug] Replying should include `References:`

### ISSUE THREAD

**Issue by Chris00** [djcb/mu#2581]
**Describe the bug**
When replying to messages, no `References:` is included, which breaks threads.

**How to Reproduce**
Just reply to a message.

**Environment**
Debian GNU/Linux
Emacs 29.1
mu commit #5b29ad8b

**Checklist**
- [x] you are running either an 1.8.x/1.10.x release or `master` (otherwise please upgrade)
- [x] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [x] you have read all of the above

**Comment by Chris00** [comment]
Also `In-Reply-To:`.

**Comment by djcb** [comment]
`In-Reply-To` is there, I think (although the header may be hidden). `References` used to be there... investigating.

**Comment by Chris00** [comment]
On  2 November 2023 at 10:53 +01, "Dirk-Jan C. Binnema" ***@***.***> wrote:
> In-Reply-To is there, I think (although the header may be hidden). References used to be there... investigating.

I'll double check too that old configuration is not interfering (I'll try later today).

**Comment by Chris00** [comment]
I checked on a message and the reply-to presently generated is `In-Reply-To: =?utf-8?Q?St=C3=A9phanie?='s message of "Thu, 02 Nov 2023 13:46:17 +0100	(1 minute, 13 seconds ago)"` while it should be the message ID, no?

**Comment by Chris00** [comment]
The problem is a consequence of [this change](https://github.com/djcb/mu/commit/9f39d78a71e302f99b4b4db1224cfef6f584a6fd#diff-502a350a77415d7668fa037c5b98cde4e342ddc8bc8f877fca4df1ee8b835682L680).  I guess it is because the decoded message does _not_ contain the necessary headers so querying them return `nil`.

**Comment by djcb** [comment]
Yeah, first we use the more-or-less raw message files, and we could extract the old Message-Id: References:, In-Reply-To: etc. from that. But! Those raw message don't have their fields decoded and because of that we got those encoded fields as per #2580.

So, to fix that we use something closer to a rendered mail as the parent message; then the fields are decode, and that fixed #2580. But this also introduced the References problem since the that header is not part of the rendered message. I've pushed some changes to allow including them... and that seems to fix it, at least for me.

**Comment by Chris00** [comment]
That does it for me too.  Thanks!

**Comment by markk** [comment]
I'm still not getting `References` in my reply buffer. Attempting to debug, but no success yet...

**Comment by Chris00** [comment]
Did you click in the menu _Field_ → _Show Hidden headers_ (`message-widen-and-recenter`)?

**Comment by markk** [comment]
Yes, and then I see `References`, `Fcc`, and `User-Agent` headers, however they are not in the email that is actually sent. Either the copy saved to the Sent folder, or the copy received.

See here: https://gist.github.com/markk/e414c17db538f646114b0f3e88f4ee2f for full headers of some test messages.

**Comment by markk** [comment]
OK, so it's actually the `In-Reply-To` header that is missing from the compose buffer. Hence the `References` header is stripped by `mu4e--compose-before-send` because `In-Reply-To` is missing.

**Comment by djcb** [comment]
When I reply to that very message (sending it to myself), I get the below message in my "sent"-folder, and the same (plus extra headers) when I receive it: 

```
From: xxx
To: xxx
Subject: Re: [djcb/mu] [mu4e bug] Replying should include `References:`
 (Issue #2581)
In-Reply-To: <djcb/mu/issues/2581/1792931824@github.com> (markk's message of
	"Fri, 03 Nov 2023 11:23:46 -0700 (1 hour, 6 minutes, 8 seconds ago)")
References: <djcb/mu/issues/2581@github.com>
	<djcb/mu/issues/2581/1792931824@github.com>
User-Agent: mu4e 1.11.24; emacs 30.0.50
Date: Fri, 03 Nov 2023 21:31:19 +0200
Message-ID: <877cmybpmg.fsf@djcbsoftware.nl>
MIME-Version: 1.0
Content-Type: text/plain

On Friday Nov 03 2023, markk wrote:

> OK, so it's actually the `In-Reply-To` header that is missing from the compose buffer. Hence the `References` header is stripped by `mu4e--compose-before-send` because `In-Reply-To` is missing.
```

Are you seeing something else?

**Comment by markk** [comment]
Yes. The "In-Reply-To" header is not being generated.

I'm reading through all the `*-compose-*` functions and trying to find at which point this header is meant to be inserted. AFAICT, `message-reply` does not add it, and neither does `mu4e--composer-setup-buffer`...

**Comment by markk** [comment]
If I add the following near the end of `mu4e--compose-setup-buffer`, then everything works fine.

```
    (when (eq mu4e-compose-type 'reply)
      (message-add-header
       (format "In-Reply-To: %s\n" (mu4e-fetch-field parent "Message-ID"))))
```

**Comment by djcb** [comment]
Manually adding  should not be needed... getting those headers is triggered by let-binding `message-required-mail-headers` in `mu4e-compose.el`.

You're seeing something else than I and @Chris00 do.... once I again, when I go this message in e-mail, pressed "R", and get a buffer with (visible after `M-x message-widen-and-recenter`):
```
In-Reply-To: <djcb/mu/issues/2581/1793433651@github.com> (markk's message of
	"Sat, 04 Nov 2023 05:45:22 -0700 (27 minutes, 7 seconds ago)")
References: <djcb/mu/issues/2581@github.com>
	<djcb/mu/issues/2581/1793433651@github.com>
[...]
```
so the question is why you are seeing something else. You do have the latest version, and are running that version?

**Comment by markk** [comment]
OK, I've tracked it down I think. `message-setup-1` will generate only the `References` header unless `message-generate-headers-first is not nil.

```
(setq message-generate-headers-first t)
```

**Comment by djcb** [comment]
I had `message-generate-headers-first` at `nil`.

But I have reworked things a bit... does it work now for you, @markk ?

**Comment by markk** [comment]
Yes, works fine with dfe28f033ad8d414497fe7586e35d5a67d8c5c8a and no explicit setting of `message-generate-headers-first`. Thanks!

**Comment by markk** [comment]
FYI still works fine with c76c410256c2c43f5fcd529982cfac0deb72cc77
