### ISSUE TITLE
[mu4e bug] Incorrect address when replying (and wrong decoding)

### ISSUE THREAD

**Issue by Chris00** [djcb/mu#2586]
**Describe the bug**
When replying to the attached message, the  `To:` field reads `To: to:cc:subject:date:message-id:reply-to`.  Note that the decoding of the cited message is also wrong.

**How to Reproduce**
Reply to the attached message.

**Environment**
Debian GNU/Linux
Emacs 29.1
Mu: commit #c3bc50bd

**Checklist**
- [x] you are running either an 1.8.x/1.10.x release or `master` (otherwise please upgrade)
- [x] you can reproduce the problem without 3rd party extensions (including Doom/Evil, various extensions etc.)
- [x] you have read all of the above

[Reply1.txt](https://github.com/djcb/mu/files/13257309/Reply1.txt)

**Comment by djcb** [comment]
Fixed.

**Comment by Chris00** [comment]
Thanks.  For me the decoding is fixed but not the `To` field.

**Comment by djcb** [comment]
When I press `R` I get:
```
In-Reply-To: 5a3fe021c0bb36bcb35542da313f64c7ef726859129a35b28eff7f498e1abd3c@mu.id
	(gabrielle@gmail.com's message of "Sat, 4 Nov 2023 17:00:21 +0100 (16
	hours, 3 minutes, 28 seconds ago)")
References: 
User-Agent: mu4e 1.11.24; emacs 30.0.50
Fcc: /home/djcb/Maildir/sent/cur/1699171429.50e610a9a7def6d6.evergrey:2,S
To: Gabrielle <gabrielle@gmail.com>
Subject: Re: 
From: "Dirk-Jan C. Binnema" <djcb@djcbsoftware.nl>
Date: Sun, 05 Nov 2023 10:03:49 +0200
Message-ID: <87cywo39ui.fsf@djcbsoftware.nl>
--text follows this line--
On Saturday Nov 04 2023, Gabrielle wrote:

> Noël.
```
are you seeing something else?

**Comment by Chris00** [comment]
The lack of `References` is due to the fact that the message I sent did not have a `Message-ID`.  When  [I add one](https://github.com/djcb/mu/files/13259077/Reply1.txt), I see a correct  `In-Reply-To:` and `References:` (maybe there should not be a `In-Reply-To:` if the message lacks a `Message-ID`):
```
In-Reply-To: <KGX92PnORaW1FtBHx7qehg@geopod-ismtpd-23> (gabrielle@gmail.com's
	message of "Sat, 04 Nov 2023 17:00:21 +0100 (17 hours, 7 minutes, 7
	seconds ago)")
References: <KGX92PnORaW1FtBHx7qehg@geopod-ismtpd-23>
User-Agent: mu4e 1.11.24; emacs 29.1
Fcc: /home/chris/Maildir/sent/cur/1699175248.11967fcf1042c64c.poincare:2,S
To: Gabrielle <gabrielle@gmail.com>
Subject: Re: 
Reply-To: Christophe@be
From: Christophe <christophe@be>
Date: Sun, 05 Nov 2023 10:07:28 +0100
Message-ID: <87il6gk1pr.fsf@poincare.be>
--text follows this line--
﻿On  4 November 2023 at 17:00 +01, Gabrielle <gabrielle@gmail.com> wrote:
> Noël.
```
Note sure where the ID in your `In-Reply-To:` header comes from.

I still see a different result when I reply from the View buffer.

**Comment by Chris00** [comment]
Beware that GH reordered the replies — my last one is https://github.com/djcb/mu/issues/2586#issuecomment-1793680442

**Comment by Chris00** [comment]
I'm seeing
```
In-Reply-To: gabrielle@gmail.com's message of "Sat, 04 Nov 2023 17:00:21 +0100
	(16 hours, 10 minutes, 5 seconds ago)"
User-Agent: mu4e 1.11.24; emacs 29.1
Fcc: /home/chris/Maildir/sent/cur/1699171826.1c165635c096540c.poincare:2,S
To: Gabrielle <gabrielle@gmail.com>
Subject: Re: 
From: Christophe <christophe@be>
Date: Sun, 05 Nov 2023 09:10:26 +0100
Message-ID: <8734xkpqml.fsf@poincare.be>
--text follows this line--
﻿On  4 November 2023 at 17:00 +01, Gabrielle <gabrielle@gmail.com> wrote:
> Noël.
```
(which is fine) if I press <kbd>R</kbd> in the `*mu4e-headers*` buffer but I see
```
To: to:cc:subject:date:message-id:reply-to
Cc: Gabrielle <gabrielle@gmail.com>
...
```
if I press <kbd>R</kbd> in the view buffer.

**Comment by djcb** [comment]
Hmm even the first case, in your example the In-reply-to: is wrong, and References: is missing. In my example, References is empty.

However, the behavior is the same from view buffer / headers buffer in my case.

**Comment by Chris00** [comment]
Beware that GH reordered the replies — my last one is https://github.com/djcb/mu/issues/2586#issuecomment-1793680442

**Comment by Chris00** [comment]
When I call  `(mu4e-view-message-text (mu4e-message-at-point) 'all-headers)` from the `*mu4e-headers*` buffer, I get
```
ARC-Message-Signature:
h=From:Date:Subject:Message-ID:Content-Type:MIME-Version:X-MS-Exchange-AntiSpam-MessageData-ChunkCount:X-MS-Exchange-AntiSpam-MessageData-0:X-MS-Exchange-AntiSpam-MessageData-1
DKIM-Signature: h=to:subject:message-id:date:from:in-reply-to:references:mime-version :
 from:to:cc:subject:date:message-id:reply-to 
MIME-Version: 1.0
Message-ID: <KGX92PnORaW1FtBHx7qehg@geopod-ismtpd-23>
From: Gabrielle <gabrielle@gmail.com>
Date: Sat, 04 Nov 2023 17:00:21 +0100 (17 hours, 30 minutes, 29 seconds ago)
Subject: Re:
To: Christophe <Christophe@be>
Content-Type: text/plain; charset=\"UTF-8\"
Maildir: /test
Size: 590

Noël.
```
but, when I do from the view buffer, I have
```
ARC-Message-Signature:
 h=From:Date:Subject:Message-ID:Content-Type:MIME-Version:X-MS-Exchange-AntiSpam-MessageData-ChunkCount:X-MS-Exchange-AntiSpam-MessageData-0:X-MS-Exchange-AntiSpam-MessageData-1
DKIM-Signature: h=to:subject:message-id:date:from:in-reply-to:references:mime-version :
from:to:cc:subject:date:message-id:reply-to 
MIME-Version: 1.0
Message-ID: <KGX92PnORaW1FtBHx7qehg@geopod-ismtpd-23>
From: Gabrielle <gabrielle@gmail.com>
Date: Sat, 04 Nov 2023 17:00:21 +0100 (17 hours, 31 minutes, 27 seconds ago)
Subject: Re:
To: Christophe <Christophe@be>
Content-Type: text/plain; charset=\"UTF-8\"
Maildir: /test
Size: 590

Noël.
```
Note the lack of space before `from` which explains the result.

**Comment by djcb** [comment]
Ah, yeah, found the same thing. The problem is 1) we should ensure the Message-Id is always there isn the mu4e-view-message-txt (regardless of `mu4e-view-fields`), and 2) The Gabrielle -message lacks a message-id, so we should use mu-generated one.

I'll make a change for this.

**Comment by Chris00** [comment]
> Note the lack of space before from which explains the result.

The change in the headers is due to calling `gnus-article-prepare-display` in `mu4e--view-render-buffer`.  It is necessary for a real view buffer but is it just to get the decoded string?

**Comment by djcb** [comment]
I'd like to _not_ do the full `gnus-article-prepare-display`, but it's a bit hard to untangle just the bits that are needed; but surely if you can find a simpler way, that'd be good!

**Comment by djcb** [comment]
I've pushed a change which indeed avoids `gnus-article-prepare-display`... does that work for you?

**Comment by Chris00** [comment]
> I've pushed a change which indeed avoids gnus-article-prepare-display... does that work for you?

Yes, this is much better.  Thanks!

**Comment by djcb** [comment]
Okay, closing this now, thanks!
